/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AddConnectionLinkComponent {
        "color": string;
        "splitter_name": string;
        "text": string;
    }
    interface BambooDetail {
    }
    interface CircuitConnection {
    }
    interface ConnectionLinkComponent {
        "splitter_name": string;
    }
}
declare global {
    interface HTMLAddConnectionLinkComponentElement extends Components.AddConnectionLinkComponent, HTMLStencilElement {
    }
    var HTMLAddConnectionLinkComponentElement: {
        prototype: HTMLAddConnectionLinkComponentElement;
        new (): HTMLAddConnectionLinkComponentElement;
    };
    interface HTMLBambooDetailElement extends Components.BambooDetail, HTMLStencilElement {
    }
    var HTMLBambooDetailElement: {
        prototype: HTMLBambooDetailElement;
        new (): HTMLBambooDetailElement;
    };
    interface HTMLCircuitConnectionElement extends Components.CircuitConnection, HTMLStencilElement {
    }
    var HTMLCircuitConnectionElement: {
        prototype: HTMLCircuitConnectionElement;
        new (): HTMLCircuitConnectionElement;
    };
    interface HTMLConnectionLinkComponentElement extends Components.ConnectionLinkComponent, HTMLStencilElement {
    }
    var HTMLConnectionLinkComponentElement: {
        prototype: HTMLConnectionLinkComponentElement;
        new (): HTMLConnectionLinkComponentElement;
    };
    interface HTMLElementTagNameMap {
        "add-connection-link-component": HTMLAddConnectionLinkComponentElement;
        "bamboo-detail": HTMLBambooDetailElement;
        "circuit-connection": HTMLCircuitConnectionElement;
        "connection-link-component": HTMLConnectionLinkComponentElement;
    }
}
declare namespace LocalJSX {
    interface AddConnectionLinkComponent {
        "color"?: string;
        "splitter_name"?: string;
        "text"?: string;
    }
    interface BambooDetail {
    }
    interface CircuitConnection {
    }
    interface ConnectionLinkComponent {
        "splitter_name"?: string;
    }
    interface IntrinsicElements {
        "add-connection-link-component": AddConnectionLinkComponent;
        "bamboo-detail": BambooDetail;
        "circuit-connection": CircuitConnection;
        "connection-link-component": ConnectionLinkComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "add-connection-link-component": LocalJSX.AddConnectionLinkComponent & JSXBase.HTMLAttributes<HTMLAddConnectionLinkComponentElement>;
            "bamboo-detail": LocalJSX.BambooDetail & JSXBase.HTMLAttributes<HTMLBambooDetailElement>;
            "circuit-connection": LocalJSX.CircuitConnection & JSXBase.HTMLAttributes<HTMLCircuitConnectionElement>;
            "connection-link-component": LocalJSX.ConnectionLinkComponent & JSXBase.HTMLAttributes<HTMLConnectionLinkComponentElement>;
        }
    }
}
